table data_clean
	lineageTag: 406088c7-972a-469c-894b-2b048691489d

	column Edad
		dataType: int64
		formatString: 0
		lineageTag: a1cbd5d4-02d9-4e12-a9da-4828f2c94020
		summarizeBy: sum
		sourceColumn: Edad

		annotation SummarizationSetBy = Automatic

	column Sexo
		dataType: string
		lineageTag: 0a63aeb4-d3e8-459d-9731-74405103e964
		summarizeBy: none
		sourceColumn: Sexo

		annotation SummarizationSetBy = Automatic

	column 'Area de Residencia'
		dataType: string
		lineageTag: 9327bc58-7252-4c04-9296-51dda3cdc99b
		summarizeBy: none
		sourceColumn: Area de Residencia

		annotation SummarizationSetBy = Automatic

	column 'Barrio de Residencia'
		dataType: string
		lineageTag: 1a29288b-85c3-41d4-b360-25372c785f30
		summarizeBy: none
		sourceColumn: Barrio de Residencia

		annotation SummarizationSetBy = Automatic

	column 'Seguridad Social'
		dataType: string
		lineageTag: c9879452-1518-4700-bd68-2a3cc5fe7fbf
		summarizeBy: none
		sourceColumn: Seguridad Social

		annotation SummarizationSetBy = Automatic

	column Estrato
		dataType: int64
		formatString: 0
		lineageTag: 795f0877-2fac-41f3-bdec-b53d1135545b
		summarizeBy: sum
		sourceColumn: Estrato

		annotation SummarizationSetBy = Automatic

	column Gestante
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c5506960-c9c6-44fd-96d8-7dbd2c5b4bcf
		summarizeBy: none
		sourceColumn: Gestante

		annotation SummarizationSetBy = Automatic

	column 'Población a cargo del ICBF'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: be4d1243-7488-4544-a82d-22eae7b5d26e
		summarizeBy: none
		sourceColumn: Población a cargo del ICBF

		annotation SummarizationSetBy = Automatic

	column 'Fecha del Hecho'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0b4f95ba-8d1a-4f25-aef8-05b0ae317c54
		summarizeBy: none
		sourceColumn: Fecha del Hecho

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Número de Intentos'
		dataType: int64
		formatString: 0
		lineageTag: aeb8740b-4503-4b80-823f-99ed7b415718
		summarizeBy: sum
		sourceColumn: Número de Intentos

		annotation SummarizationSetBy = Automatic

	column 'Estado Civil'
		dataType: string
		lineageTag: 12cbb399-5b6a-4c34-9514-154ba49852f2
		summarizeBy: none
		sourceColumn: Estado Civil

		annotation SummarizationSetBy = Automatic

	column Escolaridad
		dataType: string
		lineageTag: db018255-131b-4816-9f03-22515ce2ffb6
		summarizeBy: none
		sourceColumn: Escolaridad

		annotation SummarizationSetBy = Automatic

	column 'Enfermedad Crónica Dolorosa'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 485e69b8-8eb3-499f-9939-25924fc63224
		summarizeBy: none
		sourceColumn: Enfermedad Crónica Dolorosa

		annotation SummarizationSetBy = Automatic

	column 'Problemas Económicos'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e0fb7e31-a973-4423-b859-ac4ac75946ee
		summarizeBy: none
		sourceColumn: Problemas Económicos

		annotation SummarizationSetBy = Automatic

	column 'Muerte de Familiar'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 257ffffb-4f6a-4ad9-86d7-c7b85740dbb1
		summarizeBy: none
		sourceColumn: Muerte de Familiar

		annotation SummarizationSetBy = Automatic

	column 'Escolaridad Educativa'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d7e75d40-3d06-4209-808e-b1cc668a6474
		summarizeBy: none
		sourceColumn: Escolaridad Educativa

		annotation SummarizationSetBy = Automatic

	column 'Problemas Jurídicos'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c05eb81f-c4bc-4ead-9e46-7a670aa4974e
		summarizeBy: none
		sourceColumn: Problemas Jurídicos

		annotation SummarizationSetBy = Automatic

	column 'Suicidio de Familiar'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 63adfee7-a80f-47c5-92c1-14b20bdfb0aa
		summarizeBy: none
		sourceColumn: Suicidio de Familiar

		annotation SummarizationSetBy = Automatic

	column 'Maltrato Fisico/Psicologíco'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d0df5626-61eb-4b3d-b999-d95bf7076f88
		summarizeBy: none
		sourceColumn: Maltrato Fisico/Psicologíco

		annotation SummarizationSetBy = Automatic

	column 'Problemas Laborales'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6b50b3cb-ef1a-4f93-86a8-2b8fa9933acc
		summarizeBy: none
		sourceColumn: Problemas Laborales

		annotation SummarizationSetBy = Automatic

	column 'Problemas Familiares'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1683e4c6-611f-4942-ad1b-318fceba25c6
		summarizeBy: none
		sourceColumn: Problemas Familiares

		annotation SummarizationSetBy = Automatic

	column 'Consumo de SPA'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b75bea3b-9842-41e2-97c2-5053b42f4128
		summarizeBy: none
		sourceColumn: Consumo de SPA

		annotation SummarizationSetBy = Automatic

	column 'Pensamientos Suicidas Recurrentes'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4218df35-2dfc-4a30-a4a2-3d2c9d398c0c
		summarizeBy: none
		sourceColumn: Pensamientos Suicidas Recurrentes

		annotation SummarizationSetBy = Automatic

	column Planificado
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0f3b0d1c-bf60-4c20-bcf8-43a276e4e8aa
		summarizeBy: none
		sourceColumn: Planificado

		annotation SummarizationSetBy = Automatic

	column 'Antecedente de Trastorno Psiquiátrico'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 22058891-6d82-40b2-b4c3-ee69093a8896
		summarizeBy: none
		sourceColumn: Antecedente de Trastorno Psiquiátrico

		annotation SummarizationSetBy = Automatic

	column 'Trastorno Depresivo'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f40556a7-05cf-431b-9a62-af34486492ed
		summarizeBy: none
		sourceColumn: Trastorno Depresivo

		annotation SummarizationSetBy = Automatic

	column 'Trastorno de Personalidad'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 56243dc1-12bb-4bec-ab72-4948a9399f27
		summarizeBy: none
		sourceColumn: Trastorno de Personalidad

		annotation SummarizationSetBy = Automatic

	column 'Trastorno Bipolar'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 25d551c6-895e-4dbd-811c-47017f76eed1
		summarizeBy: none
		sourceColumn: Trastorno Bipolar

		annotation SummarizationSetBy = Automatic

	column Esquizofrenia
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4e6378d0-5ebb-4e58-bdd6-66c3dcf4b0c3
		summarizeBy: none
		sourceColumn: Esquizofrenia

		annotation SummarizationSetBy = Automatic

	column 'Antecedente de Violencia o Abuso'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 925e8162-2693-4aa9-a70f-93abfd247c75
		summarizeBy: none
		sourceColumn: Antecedente de Violencia o Abuso

		annotation SummarizationSetBy = Automatic

	column 'Abuso de Alcohol'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: faed2530-d114-4756-9cf7-06dfe46a6c66
		summarizeBy: none
		sourceColumn: Abuso de Alcohol

		annotation SummarizationSetBy = Automatic

	column Ahorcamiento
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: bfca2fd8-7f0b-45e7-87d5-1ee3c8ec2b57
		summarizeBy: none
		sourceColumn: Ahorcamiento

		annotation SummarizationSetBy = Automatic

	column 'Arma Cortopunzante'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6d02cb55-4fc0-48e4-9e4a-9df47f5ec857
		summarizeBy: none
		sourceColumn: Arma Cortopunzante

		annotation SummarizationSetBy = Automatic

	column 'Arma de Fuego'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4dbf08ef-d51c-4832-8765-68b4c0e13325
		summarizeBy: none
		sourceColumn: Arma de Fuego

		annotation SummarizationSetBy = Automatic

	column Inmolación
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8b142caf-a8a8-411b-ac2a-bd0d7ee68d92
		summarizeBy: none
		sourceColumn: Inmolación

		annotation SummarizationSetBy = Automatic

	column 'Lanzamiento al Vacío'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: acb30b89-8ee1-451f-bdc4-d9a839d8d843
		summarizeBy: none
		sourceColumn: Lanzamiento al Vacío

		annotation SummarizationSetBy = Automatic

	column 'Lanzamiento a Vehículo'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8333ea56-cd68-4805-8d40-988d262b4c93
		summarizeBy: none
		sourceColumn: Lanzamiento a Vehículo

		annotation SummarizationSetBy = Automatic

	column 'Lanzamiento al Agua'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f59df0df-a21c-41d6-94aa-592231ae31cb
		summarizeBy: none
		sourceColumn: Lanzamiento al Agua

		annotation SummarizationSetBy = Automatic

	column Intoxicaciones
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 87d8e508-c3a9-4a8e-8b59-91ef08094821
		summarizeBy: none
		sourceColumn: Intoxicaciones

		annotation SummarizationSetBy = Automatic

	column 'Remitido a Psiquiatría'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6aff1959-5f86-4b34-bf06-de392e40e48b
		summarizeBy: none
		sourceColumn: Remitido a Psiquiatría

		annotation SummarizationSetBy = Automatic

	column 'Remitido a Psicología'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 600114a0-a111-4e83-a5b1-7fd1b925b7c1
		summarizeBy: none
		sourceColumn: Remitido a Psicología

		annotation SummarizationSetBy = Automatic

	column 'Remitido a Trabajo Social'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: fc48a252-0f50-412d-a54b-17178fa10849
		summarizeBy: none
		sourceColumn: Remitido a Trabajo Social

		annotation SummarizationSetBy = Automatic

	column 'Fecha de Notificación'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 01deb6c2-8b08-43bf-9168-c583fed55141
		summarizeBy: none
		sourceColumn: Fecha de Notificación

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Conflictos de Pareja'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2fdcc05e-4794-43f8-9b66-69161e2d583c
		summarizeBy: none
		sourceColumn: Conflictos de Pareja

		annotation SummarizationSetBy = Automatic

	column 'Antecedentes Familiares con conducto Suicida'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0db3d726-cc14-4fad-a0f0-8ad94cc11f7c
		summarizeBy: none
		sourceColumn: Antecedentes Familiares con conducto Suicida

		annotation SummarizationSetBy = Automatic

	partition data_clean = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents(#"Directorio del Archivo" & #"Nombre del Archivo"),[Delimiter=",", Columns=49, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"fecha_de_notificacion", type date}, {"edad_de_la_victima", Int64.Type}, {"estrato_socioeconomico", Int64.Type}, {"gestante", type logical}, {"poblacion_a_cargo_icbf", type logical}, {"fecha_del_hecho", type date}, {"numero_de_intentos", Int64.Type}, {"conflictos_pareja", type logical}, {"enfermedad_cronica_dolorosa", type logical}, {"problemas_economicos", type logical}, {"muerte_de_un_familiar", type logical}, {"escolar_educativa", type logical}, {"problemas_juridicos", type logical}, {"suicidio_de_un_familiar", type logical}, {"maltrato_fisico_sicologico", type logical}, {"problemas_laborales", type logical}, {"problemas_familiares", type logical}, {"consumo_de_spa", type logical}, {"familiares_cond_suicida", type logical}, {"ideacion_suicida_persistente", type logical}, {"plan_organizado_de_suicidio", type logical}, {"antecedente_trastorno", type logical}, {"trastorno_depresivo", type logical}, {"trastorno_de_personalidad", type logical}, {"trastorno_bipolar", type logical}, {"esquizofrenia", type logical}, {"antecedente_violencia_o_abuso", type logical}, {"abuso_de_alcohol", type logical}, {"ahorcamiento", type logical}, {"arma_cortopunzante", type logical}, {"arma_de_fuego", type logical}, {"inmolacion", type logical}, {"lanzamiento_al_vacio", type logical}, {"lanzamiento_a_vehiculo", type logical}, {"lanzamiento_al_agua", type logical}, {"intoxicaciones", type logical}, {"remitido_a_psiquiatria", type logical}, {"remitido_a_psicologia", type logical}, {"remitido_a_trabajo_social", type logical}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"", "_1", "_2", "_3"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas quitadas",{{"fecha_de_notificacion", "Fecha de Notificación"}, {"edad_de_la_victima", "Edad"}, {"sexo", "Sexo"}, {"area_de_residencia", "Area de Residencia"}, {"barrio_de_residencia", "Barrio de Residencia"}, {"seguridad_social", "Seguridad Social"}, {"estrato_socioeconomico", "Estrato"}, {"gestante", "Gestante"}, {"poblacion_a_cargo_icbf", "Población a cargo del ICBF"}, {"fecha_del_hecho", "Fecha del Hecho"}, {"numero_de_intentos", "Número de Intentos"}, {"estado_civil", "Estado Civil"}, {"escolaridad", "Escolaridad"}, {"conflictos_pareja", "Conflictos de Pareja"}, {"enfermedad_cronica_dolorosa", "Enfermedad Crónica Dolorosa"}, {"problemas_economicos", "Problemas Económicos"}, {"muerte_de_un_familiar", "Muerte de Familiar"}, {"escolar_educativa", "Escolaridad Educativa"}, {"problemas_juridicos", "Problemas Jurídicos"}, {"suicidio_de_un_familiar", "Suicidio de Familiar"}, {"maltrato_fisico_sicologico", "Maltrato Fisico/Psicologíco"}, {"problemas_laborales", "Problemas Laborales"}, {"problemas_familiares", "Problemas Familiares"}, {"consumo_de_spa", "Consumo de SPA"}, {"familiares_cond_suicida", "Antecedentes Familiares con conducto Suicida"}, {"ideacion_suicida_persistente", "Pensamientos Suicidas Recurrentes"}, {"plan_organizado_de_suicidio", "Planificado"}, {"antecedente_trastorno", "Antecedente de Trastorno Psiquiátrico"}, {"trastorno_depresivo", "Trastorno Depresivo"}, {"trastorno_de_personalidad", "Trastorno de Personalidad"}, {"trastorno_bipolar", "Trastorno Bipolar"}, {"esquizofrenia", "Esquizofrenia"}, {"antecedente_violencia_o_abuso", "Antecedente de Violencia o Abuso"}, {"abuso_de_alcohol", "Abuso de Alcohol"}, {"ahorcamiento", "Ahorcamiento"}, {"arma_cortopunzante", "Arma Cortopunzante"}, {"arma_de_fuego", "Arma de Fuego"}, {"inmolacion", "Inmolación"}, {"lanzamiento_al_vacio", "Lanzamiento al Vacío"}, {"lanzamiento_a_vehiculo", "Lanzamiento a Vehículo"}, {"lanzamiento_al_agua", "Lanzamiento al Agua"}, {"intoxicaciones", "Intoxicaciones"}, {"remitido_a_psiquiatria", "Remitido a Psiquiatría"}, {"remitido_a_psicologia", "Remitido a Psicología"}, {"remitido_a_trabajo_social", "Remitido a Trabajo Social"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

