name: Verificar CSV en directorio

on:
  push:
    branches: [main]
    paths: ['data/*.csv']
  pull_request:
    branches: [main]
    paths: ['data/*.csv']

jobs:

  check_csv:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.6'
      
      - name: Instalar Dependencias
        run: pip install pandas
      
      - name: Validar archivos CSV
        run: python .github/scripts/check_csv.py